package com.todo;

import org.apache.commons.lang3.CharUtils;

import com.todo.utils.CommandLineInput;
import com.todo.utils.CommandLineInputHandler;

/*
 * This Java source file was generated by the Gradle 'init' task.
 * ToDoApp 的主类
 *
 *
 */
public class ToDoApp {

	public static final char DEFAULT_INPUT = '\u0000';

	public static void main(String[] args) {
		CommandLineInputHandler commandLineInputHandler = new CommandLineInputHandler();
        char command = DEFAULT_INPUT;

        while(CommandLineInput.EXIT.getShortCmd() != command) {
        		//输出提示信息
            commandLineInputHandler.printOptions();
            //读取用户输入
            String input = commandLineInputHandler.readInput();
            //如果用户输入1个字符就将其转为char数组，否则使用默认的输入
            //char[] inputChars = input.length() == 1 ? input.toCharArray() : new char[] { DEFAULT_INPUT };
            //获取命令
            //command = inputChars[0];
            
            //使用lang3包中的CharUtils.tochar() 更优雅的完成字符串的转换。代替上面两句话。
            command = CharUtils.toChar(input, DEFAULT_INPUT);
           
            //将输入转为枚举
            CommandLineInput commandLineInput = CommandLineInput.getCommandLineInputForInput(command);
            //执行命令
            commandLineInputHandler.processInput(commandLineInput);
        }
	}
}
